### ISSUE TITLE
Service daikinskyport.daikin_resume_program does not work

### ISSUE THREAD

**Issue by knightjoel** [apetrycki/daikinskyport#14]
When calling `daikinskyport.daikin_resume_program`, the following is logged in home-assistant.log:

```
2021-06-29 15:16:43 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'Thermostat' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 368, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 568, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/daikinskyport/climate.py", line 176, in resume_program_set_service
    thermostat.resume_program(thermostat["id"])
TypeError: 'Thermostat' object is not subscriptable
```

**Comment by knightjoel** [comment]
I think this would be enough to fix the exception. Requires testing to see if it actually affects the thermostat's behavior.

```
index 063e4a5..27ab15d 100644
--- a/custom_components/daikinskyport/climate.py
+++ b/custom_components/daikinskyport/climate.py
@@ -173,7 +173,7 @@ def setup_platform(hass, config, add_entities, discovery_info=None):
             target_thermostats = devices

         for thermostat in target_thermostats:
-            thermostat.resume_program(thermostat["id"])
+            thermostat.resume_program()

             thermostat.schedule_update_ha_state(True)
```

**Comment by apetrycki** [comment]
That looks like it works.  My thermostat went back to schedule mode after initiating the service call.  Good catch!

**Comment by knightjoel** [comment]
Awesome!
