### ISSUE TITLE
Integration appears broken in 2022.08.05

### ISSUE THREAD

**Issue by adwoodworth** [apetrycki/daikinskyport#48]
I suspect some JSON handling issues based on the traceback in log files:

Error during setup of component daikinskyport
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/daikinskyport/__init__.py", line 72, in setup
    data = DaikinSkyportData(hass.config.path(DAIKINSKYPORT_CONFIG_FILE))
  File "/config/custom_components/daikinskyport/__init__.py", line 49, in __init__
    self.daikinskyport = DaikinSkyport(config_file)
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 55, in __init__
    config = config_from_file(config_filename)
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 31, in config_from_file
    return json.loads(fdesc.read())
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by adwoodworth** [comment]
Deleting the daikinskyport.conf file and restarting the integration appears to resolve the issue.

**Comment by livefeed** [comment]
@adwoodworth Still not working for me even after the delete mmmmmm
