### ISSUE TITLE
Home Assistant 2023.4.2

### ISSUE THREAD

**Issue by unc2k3** [apetrycki/daikinskyport#57]
Previously had this working until the update to 2023.4 broke the integration.  Noticed this was fixed in the recent update.  I completely removed the integration while waiting on the update and have since reinstalled per the Github instructions.  Unfortunately, the entities are not showing up at all now.

**Comment by livefeed** [comment]
Same here, no longer working :(

**Comment by apetrycki** [comment]
Need more info than "it doesn't work".  Did you debug the logs? Did you delete the daikinskyport.conf?  Have you tried the API documentation to make sure you can poll the thermostat manually?  I'm running 2023.4.5 and it's working fine.

**Comment by livefeed** [comment]
Great, got your attention!

I have tried a reinstall and had deleted the .conf.
My .yaml is set as per instructions.

This is the error I am seeing;

Error during setup of component daikinskyport
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/daikinskyport/__init__.py", line 72, in setup
    data = DaikinSkyportData(hass.config.path(DAIKINSKYPORT_CONFIG_FILE))
  File "/config/custom_components/daikinskyport/__init__.py", line 49, in __init__
    self.daikinskyport = DaikinSkyport(config_file)
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 78, in __init__
    self.update()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 226, in update
    self.get_thermostats()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 148, in get_thermostats
    if self.refresh_tokens():
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 117, in refresh_tokens
    self.request_tokens()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 85, in request_tokens
    data = {"email": self.user_email, "password": self.user_password}
AttributeError: 'DaikinSkyport' object has no attribute 'user_password'

**Comment by apetrycki** [comment]
This problem should be resolved by shutting down HA and deleting the conf file. It's because your token has expired and the integration doesn't store the password in the conf file. I could store the password in the conf file, but it was voted not to.

**Comment by livefeed** [comment]
@apetrycki thank you for the reply - all fixed. My Daikin account was acting up so set up a different email and input that info and worked. Thanks for your work.
