### ISSUE TITLE
Can't use my Daikin One Thermostats as of the last update to HA

### ISSUE THREAD

**Issue by IceDraken** [apetrycki/daikinskyport#60]
Here's the error from my log:
I did try redownloading, and making sure my configuration for my email and password is correct.
If it's something I can easily fix, please let me know... but the google search on the "async" thing appears there were some back end changes in HA that may have broken it.

***Start***
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/daikinskyport/daikinskyport.py:31
Integration: daikinskyport (documentation, issues)
First occurred: 12:22:41 AM (1 occurrences)
Last logged: 12:22:41 AM

Error during setup of component daikinskyport
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 72, in setup
    data = DaikinSkyportData(hass.config.path(DAIKINSKYPORT_CONFIG_FILE))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 49, in __init__
    self.daikinskyport = DaikinSkyport(config_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 55, in __init__
    config = config_from_file(config_filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 31, in config_from_file
    return json.loads(fdesc.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
**End***

**Comment by IceDraken** [comment]
HA Information:
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by IceDraken** [comment]
They are back... this can be closed.
I had to re-delete the .conf file for some reason... took a few reboots and changing my password in their app while HA was shut down after deleting the .conf.  BUT it worked.
