### ISSUE TITLE
Daikin integration broken after upgrading to 2023.9.2. Even rolling back to 8.4 did not fix it.

### ISSUE THREAD

**Issue by enkrypt3d** [apetrycki/daikinskyport#68]
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.setup
Source: custom_components/daikinskyport/daikinskyport.py:85
Integration: daikinskyport ([documentation](https://github.com/apetrycki/daikinskyport), [issues](https://github.com/apetrycki/daikinskyport/issues))
First occurred: September 14, 2023 at 10:40:40 PM (1 occurrences)
Last logged: September 14, 2023 at 10:40:40 PM

Error during setup of component daikinskyport
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 72, in setup
    data = DaikinSkyportData(hass.config.path(DAIKINSKYPORT_CONFIG_FILE))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 49, in __init__
    self.daikinskyport = DaikinSkyport(config_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 78, in __init__
    self.update()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 225, in update
    self.get_thermostats()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 148, in get_thermostats
    if self.refresh_tokens():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 117, in refresh_tokens
    self.request_tokens()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 85, in request_tokens
    data = {"email": self.user_email, "password": self.user_password}
                                                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'DaikinSkyport' object has no attribute 'user_password'

**Comment by apetrycki** [comment]
This one has been brought up numerous times.  Delete the daikinskyport.conf file and it'll fix it.  Alternatively, you can try the new version of the integration I'm working on in the ui_config branch that no longer uses the file.

**Comment by enkrypt3d** [comment]
Every time I delete that file and restart HA, the file comes back and the integration shows unavailable......
