### ISSUE TITLE
No longer can configure

### ISSUE THREAD

**Issue by biofects** [apetrycki/daikinskyport#80]
Hello,
I updated via HACS and now my Diakin is unavailable and I get this error
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/daikinskyport/daikinskyport.py:171
Integration: Daikin Skyport (documentation, issues)
First occurred: 10:08:38 AM (5 occurrences)
Last logged: 11:08:23 AM

Error setting up entry Daikin for daikinskyport
Traceback (most recent call last):
  File "/config/custom_components/daikinskyport/__init__.py", line 161, in _async_update_data
    current = await self.hass.async_add_executor_job(self.daikinskyport.update)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 259, in update
    result = self.get_thermostats()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 171, in get_thermostats
    raise ExpiredTokenError ("Daikin Skyport token expired")
custom_components.daikinskyport.daikinskyport.ExpiredTokenError: Daikin Skyport token expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 79, in async_setup_entry
    await coordinator._async_update_data()
  File "/config/custom_components/daikinskyport/__init__.py", line 165, in _async_update_data
    await self.hass.async_add_executor_job(self.daikinskyport.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 259, in update
    result = self.get_thermostats()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 171, in get_thermostats
    raise ExpiredTokenError ("Daikin Skyport token expired")
custom_components.daikinskyport.daikinskyport.ExpiredTokenError: Daikin Skyport token expired

**Comment by biofects** [comment]
update, I have changed password now I get this error 

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:202
First occurred: 11:25:35 AM (3 occurrences)
Last logged: 11:25:35 AM

Error unloading entry Daikin for sensor
Error unloading entry Daikin for weather
Error unloading entry Daikin for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 544, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 138, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by biofects** [comment]
Ok I guess I should have upgraded home assistant. My bad.
