### ISSUE TITLE
Integration not functioning for the past week

### ISSUE THREAD

**Issue by molohov** [apetrycki/daikinskyport#96]
Saw this error in my logs today:

```
Logger: homeassistant.setup
Source: setup.py:332
First occurred: February 8, 2024 at 8:51:34 AM (1 occurrences)
Last logged: February 8, 2024 at 8:51:34 AM

Error during setup of component daikinskyport
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 72, in setup
    data = DaikinSkyportData(hass.config.path(DAIKINSKYPORT_CONFIG_FILE))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/__init__.py", line 49, in __init__
    self.daikinskyport = DaikinSkyport(config_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 78, in __init__
    self.update()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 226, in update
    self.get_thermostats()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 148, in get_thermostats
    if self.refresh_tokens():
       ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 117, in refresh_tokens
    self.request_tokens()
  File "/config/custom_components/daikinskyport/daikinskyport.py", line 85, in request_tokens
    data = {"email": self.user_email, "password": self.user_password}
                                                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'DaikinSkyport' object has no attribute 'user_password'
```

**Comment by apetrycki** [comment]
Looks like you are running a really old version of the integration. It doesn't use the file anymore. Delete everything and redownload from HACS. The latest version now requires HA 2024.2.

**Comment by molohov** [comment]
Ah shoot my bad. I was using my forked version. Sorry about that
