### ISSUE TITLE
Unexpected exception importing platform custom_components.daikinskyport.climate

### ISSUE THREAD

**Issue by molohov** [apetrycki/daikinskyport#97]
```
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 8:34:35 PM (1 occurrences)
Last logged: 8:34:35 PM

Unexpected exception importing platform custom_components.daikinskyport.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/daikinskyport/climate.py", line 222, in <module>
    | ClimateEntityFeature.TURN_ON
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_ON

Logger: homeassistant.setup
Source: setup.py:403
First occurred: 8:34:35 PM (1 occurrences)
Last logged: 8:34:35 PM

Unable to prepare setup for platform 'daikinskyport.climate': Platform not found (Exception importing custom_components.daikinskyport.climate).
```

**Comment by apetrycki** [comment]
you have to use 2024.02 version of HA.  This integration doesn't work with anything older anymore.

**Comment by molohov** [comment]
Thanks! I just so happened to run Watchtower after posting this issue, and that updated HA for me. Thanks for the quick responses, as always
